//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM.Domain
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Todo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Todo()
        {
            this.Tomatoes = new HashSet<Tomato>();
        }
    
        public string TodoID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> NeedTomato { get; set; }
        public Nullable<int> DoneTomato { get; set; }
        public Nullable<bool> IsFinish { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Updator { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tomato> Tomatoes { get; set; }
    }
}
