//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tomato
    {
        public string TomatoID { get; set; }
        public string TodoID { get; set; }
        public string SpentTime { get; set; }
        public string CreateTime { get; set; }
        public string FinishTime { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<int> PauseCount { get; set; }
    
        public virtual Todo Todo { get; set; }
    }
}
